/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

import (
	"time"
)

// NotificationIntegration TODO Godoc comment
type NotificationIntegration struct {
	Applicability   string            `json:"applicability,omitempty"` // TODO Enum: [ NONE, USE_ALWAYS ]
	CreateDate      time.Time         `json:"createDate,omitempty"`
	CreatedByOwner  bool              `json:"createdByOwner,omitempty"`
	CreatorID       int64             `json:"creatorId,omitempty"`
	ID              int64             `json:"id,omitempty"`
	IntegrationType string            `json:"integrationType,omitempty"` // TODO Enum:[ PAGER_DUTY, NAGIOS, WEB_HOOKS, WEB_HOOKS_TEMPLATE, HIP_CHAT, EMAIL_LIST, TEMPORARY_EMAIL_LIST ]
	Name            string            `json:"name,omitempty"`
	Params          map[string]string `json:"params,omitempty"`
	State           string            `json:"state,omitempty"` // TODO Enum: [ ACTIVE, DISABLED, DELETED ]
	UserID          int64             `json:"userId,omitempty"`
}
