/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

import (
	"time"
)

// ReportInfo TODO godoc comment
type ReportInfo struct {
	// Comma separated list of email addresses
	Addresses  string    `json:"addresses,omitempty"`
	AppID      int64     `json:"appId,omitempty"`
	EndDate    time.Time `json:"endDate,omitempty"`
	Filters    string    `json:"filters,omitempty"`
	ReportName string    `json:"reportName,omitempty"`
	StartDate  time.Time `json:"startDate,omitempty"`
	Subject    string    `json:"subject,omitempty"`
	Text       string    `json:"text,omitempty"`
}
