/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

// TODO Adjust methods to use new client

import (
	"fmt"
)

//App TODO Godoc Comment
type App struct {
	AjaxThreshold         int64                 `json:"ajaxThreshold,omitempty"`
	AppType               string                `json:"appType,omitempty"`
	AppTypeID             int64                 `json:"appTypeId,omitempty"`
	CreatorEmail          string                `json:"creatorEmail,omitempty"`
	CreditCardExpiry      string                `json:"creditCardExpiry,omitempty"`
	CreditCardNumber      string                `json:"creditCardNumber,omitempty"`
	Description           string                `json:"description,omitempty"`
	DisplayStatus         string                `json:"displayStatus,omitempty"`
	FirstDataSavedDate    int64                 `json:"firstDataSavedDate,omitempty"`
	ID                    int64                 `json:"id,omitempty"`
	Integration           *ServiceIntegration   `json:"integration,omitempty"`
	LastDataReceivedDate  int64                 `json:"lastDataReceivedDate,omitempty"`
	LastDataSavedDate     int64                 `json:"lastDataSavedDate,omitempty"`
	LoggedInUserAppRole   string                `json:"loggedInUserAppRole,omitempty"`
	MonthlyInvoiceAccount bool                  `json:"monthlyInvoiceAccount,omitempty"`
	Name                  string                `json:"name,omitempty"`
	OwnerEmail            string                `json:"ownerEmail,omitempty"`
	OwningOrganization    *BasicOrganizationDto `json:"owningOrganization,omitempty"`
	PageLoadThreshold     int64                 `json:"pageLoadThreshold,omitempty"`
	PaymentMethodID       int64                 `json:"paymentMethodId,omitempty"`
	Plan                  *Plan                 `json:"plan,omitempty"`
	PrepaidAccount        bool                  `json:"prepaidAccount,omitempty"`
	Status                string                `json:"status,omitempty"`
	Token                 string                `json:"token,omitempty"`
	TrialEndDate          int64                 `json:"trialEndDate,omitempty"`
	URLGroupLimit         int32                 `json:"urlGroupLimit,omitempty"`
	UserRoles             []UserRole            `json:"userRoles,omitempty"`
}

// IsArchived TODO Doc comment
func (app *App) IsArchived() bool {

	fmt.Println("---------------------------------------")
	fmt.Println("App.IsArchived Called")
	fmt.Println("---------------------------------------")

	return app.Status == "ARCHIVED"
}
