/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

import "encoding/json"

// CreateAppInfo TODO goddoc comment
type CreateAppInfo struct {
	AppType       string `json:"appType,omitempty"`
	DiscountCode  string `json:"discountCode,omitempty"`
	InitialPlanID int64  `json:"initialPlanId,omitempty"`
	// AWS app meta data. Applicable only for `aws` appType
	MetaData *AppMetadata `json:"metaData,omitempty"`
	Name     string       `json:"name,omitempty"`
}

// Persist TODO Doc comment
func (createAppInfo *CreateAppInfo) Persist(client *Client) (*App, error) {

	var path string

	switch createAppInfo.AppType {
	case "Logsene":
		path = "/logsene-reports/api/v3/apps"
	default:
		path = "/spm-reports/api/v3/apps"
	}

	genericAPIResponse, err := client.PostJSON(path, createAppInfo)
	if err != nil {
		return nil, err
	}

	var extract interface{}
	extract, err = json.Marshal(genericAPIResponse.Data.Apps)

	var apps []App

	err = json.Unmarshal(extract.([]byte), &apps) // TODO check this conversion
	if err != nil {
		return nil, err
	}

	return &apps[0], nil
}

// IsValid TODO Doc comment
func (createAppInfo *CreateAppInfo) IsValid() bool {

	// TODO - test minimum viable

	return true
}
