/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

// CloudWatchSettings TODO godoc comment
type CloudWatchSettings struct {
	AccessKey      string `json:"accessKey,omitempty"`
	FetchFrequency string `json:"fetchFrequency,omitempty"` // TODO Enum:[ MINUTE, FIVE_MINUTES, FIFTEEN_MINUTES ]
	Region         string `json:"region,omitempty"`         // TODO Enum: [ US_EAST_1, US_WEST_1, EU_WEST_1, US_WEST_2, AP_SOUTHEAST_1, AP_SOUTHEAST_2, AP_NORTHEAST_1, SA_EAST_1, GovCloud, CN_NORTH_1, US_EAST_2, AP_SOUTH_1, AP_NORTHEAST_2, CA_CENTRAL_1, EU_CENTRAL_1, EU_WEST_2 ]
	SecretKey      string `json:"secretKey,omitempty"`
}
