/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

// AlertNotificationRequest TODO godoc comment
type AlertNotificationRequest struct {
	DefaultInterval int64  `json:"defaultInterval,omitempty"`
	End             string `json:"end,omitempty"` // End time of interval. Can be expressed as timestamp in milliseconds or UTC date in yyyy-MM-dd HH:mm:ss format
	Interval        string `json:"interval,omitempty"`
	Start           string `json:"start,omitempty"` // Start time of interval. Can be expressed as timestamp in milliseconds or UTC date in yyyy-MM-dd HH:mm:ss format
}
