/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

// TODO Adjust methods to use new client

import (
	"fmt"

	"github.com/davecgh/go-spew/spew"
)

//App TODO Godoc Comment
type App struct {
	AjaxThreshold         int64                 `json:"ajaxThreshold,omitempty"`
	AppType               string                `json:"appType,omitempty"`
	AppTypeID             int64                 `json:"appTypeId,omitempty"`
	CreatorEmail          string                `json:"creatorEmail,omitempty"`
	CreditCardExpiry      string                `json:"creditCardExpiry,omitempty"`
	CreditCardNumber      string                `json:"creditCardNumber,omitempty"`
	Description           string                `json:"description,omitempty"`
	DisplayStatus         string                `json:"displayStatus,omitempty"`
	FirstDataSavedDate    int64                 `json:"firstDataSavedDate,omitempty"`
	ID                    int64                 `json:"id,omitempty"`
	Integration           *ServiceIntegration   `json:"integration,omitempty"`
	LastDataReceivedDate  int64                 `json:"lastDataReceivedDate,omitempty"`
	LastDataSavedDate     int64                 `json:"lastDataSavedDate,omitempty"`
	LoggedInUserAppRole   string                `json:"loggedInUserAppRole,omitempty"`
	MonthlyInvoiceAccount bool                  `json:"monthlyInvoiceAccount,omitempty"`
	Name                  string                `json:"name,omitempty"`
	OwnerEmail            string                `json:"ownerEmail,omitempty"`
	OwningOrganization    *BasicOrganizationDto `json:"owningOrganization,omitempty"`
	PageLoadThreshold     int64                 `json:"pageLoadThreshold,omitempty"`
	PaymentMethodID       int64                 `json:"paymentMethodId,omitempty"`
	Plan                  *Plan                 `json:"plan,omitempty"`
	PrepaidAccount        bool                  `json:"prepaidAccount,omitempty"`
	Status                string                `json:"status,omitempty"`
	Token                 string                `json:"token,omitempty"`
	TrialEndDate          int64                 `json:"trialEndDate,omitempty"`
	URLGroupLimit         int32                 `json:"urlGroupLimit,omitempty"`
	UserRoles             []UserRole            `json:"userRoles,omitempty"`
}

// Load TODO Doc comment
func (app *App) Load(id int, client *Client) (*App, error) {

	fmt.Println("---------------------------------------")
	fmt.Println("App.Load Called")
	fmt.Println("---------------------------------------")

	var genericAPIResponse *GenericAPIResponse
	var err error

	path := fmt.Sprintf("/users-web/api/v3/apps/%d", id)
	fmt.Println("---------------------------------------")
	fmt.Println("path")
	fmt.Println(path)
	fmt.Println("---------------------------------------")

	if genericAPIResponse, err = client.GetJSON(path, nil); err != nil {
		return nil, err
	}

	fmt.Println("---------------------------------------")
	fmt.Println("genericAPIResponse")
	spew.Dump(genericAPIResponse)
	fmt.Println("---------------------------------------")

	if app, err = genericAPIResponse.ExtractApp(); err != nil {
		return nil, err
	}

	fmt.Println("---------------------------------------")
	fmt.Println("app")
	spew.Dump(app)
	fmt.Println("---------------------------------------")

	return app, nil

}

// Retired TODO Doc comment
func (app *App) Retired(id int, client *Client) (bool, error) {

	fmt.Println("---------------------------------------")
	fmt.Println("App.Retired Called")
	fmt.Println("---------------------------------------")

	var err error
	if app, err = app.Load(id, client); err != nil {
		return false, err // TODO Correct to call false on error - tristate condition?
	}
	exists := app != nil && !app.IsArchived()

	return exists, nil

}

// Persist TODO Doc comment
func (app *App) Persist(id int, client *Client, updateAppInfo UpdateAppInfo) (*App, error) {

	fmt.Println("---------------------------------------")
	fmt.Println("App.Persist Called")
	fmt.Println("---------------------------------------")

	var genericAPIResponse *GenericAPIResponse
	var err error

	path := fmt.Sprintf("/spm-reports/api/v3/apps/%d", id)
	if genericAPIResponse, err = client.PutJSON(path, updateAppInfo); err != nil {
		return nil, err
	}

	if app, err = genericAPIResponse.ExtractAppByID(id); err != nil {
		return nil, err
	}

	return app, nil
}

// IsArchived TODO Doc comment
func (app *App) IsArchived() bool {

	fmt.Println("---------------------------------------")
	fmt.Println("App.IsArchived Called")
	fmt.Println("---------------------------------------")

	return app.Status == "ARCHIVED"
}
