/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

import (
	"fmt"
)

// GenericAPIResponse is a generic wrapper class for all API responses
type GenericAPIResponse struct {
	// Contains actual data when response is successful. Key and Value is specific to each endpoint
	Data    *interface{} `json:"data,omitempty"`
	Errors  []ModelError `json:"errors,omitempty"`
	Message string       `json:"message,omitempty"`
	Success bool         `json:"success,omitempty"`
}

// ExtractApp - TODO Doc Comment
func (genericAPIResponse *GenericAPIResponse) ExtractApp() (*App, error) {

	data := (*genericAPIResponse.Data).(map[string]App)

	if app, ok := data["App"]; ok {
		return &app, nil
	}

	return nil, fmt.Errorf("Unexpected missing App field in API response")

}
