/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

import (
	"fmt"

	"github.com/mitchellh/mapstructure"
)

// GenericAPIResponse is a generic wrapper class for all API responses
type GenericAPIResponse struct {
	// Contains actual data when response is successful. Key and Value is specific to each endpoint
	Data    *interface{} `json:"data,omitempty"`
	Errors  []ModelError `json:"errors,omitempty"`
	Message string       `json:"message,omitempty"`
	Success bool         `json:"success,omitempty"`
}

// ExtractApp - TODO Doc Comment
func (genericAPIResponse *GenericAPIResponse) ExtractApp() (*App, error) {

	// TODO - Shift this to TFP?

	var dataEntry map[string]interface{}
	var appsEntry []interface{}
	var appEntry map[string]interface{}
	var exists bool
	var app App

	dataEntry = (*genericAPIResponse.Data).(map[string]interface{})

	if appsEntry, exists = dataEntry["apps"].([]interface{}); exists {

		mapstructure.Decode(appsEntry[0], &app)
		return &app, nil

	} else if appEntry, exists = dataEntry["app"].(map[string]interface{}); exists {

		mapstructure.Decode(appEntry, &app)
		return &app, nil

	} else {

		return nil, fmt.Errorf("Unexpected missing apps or app field in API response")

	}

}
