/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

import "fmt"

// BillingInfo TODO godoc Comment
type BillingInfo struct {
	// CreditCardId int64 `json:"creditCardId,omitempty"` Not Implemented
	// PaymentMethod string `json:"paymentMethod,omitempty"` Not Implemented
	PlanID int64 `json:"planId,omitempty"`
}

// TODO Adjust for new client

// Persist TODO Doc comment
func (billingInfo *BillingInfo) Persist(appID int, client *Client) error {

	path := fmt.Sprintf("/users-web/api/v3/billing/info/%d", appID)

	_, err := client.PutJSON(path, billingInfo)
	if err != nil {
		return err // TODO Extract information from genericAPIResponse
	}

	// TODO Check http status and other return errors.

	return nil
}

// IsValid TODO Doc comment
func (billingInfo *BillingInfo) IsValid() (valid bool, err error) {

	// TODO - test minimum viable

	return true, nil
}
