/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

// DataSeriesRequest TODO Godoc comment
type DataSeriesRequest struct {
	DefaultInterval int64 `json:"defaultInterval,omitempty"`

	// End time of interval. Can be expressed as timestamp in milliseconds or UTC date in yyyy-MM-dd HH:mm:ss format
	End string `json:"end,omitempty"`

	// Map of allowed filter values and aggregation strategy. List of available filter values can be fetched using metric filters endpoint and default aggregation strategy depends on metric
	Filters map[string]DataSeriesFilter `json:"filters,omitempty"`

	// Data points interval granularity between two data points.Default value is \"AUTO\" - calculated based on selected time span. Not required while getting filters.
	Granularity string `json:"granularity,omitempty"` // TODO Enum:[ AUTO, ONE_MINUTE, FIVE_MINUTES, HOUR, DAY, WEEK, MONTH ]

	Interval string `json:"interval,omitempty"`

	// Metric name or metric group prefix
	Metric string `json:"metric"`

	// Start time of interval. Can be expressed as timestamp in milliseconds or UTC date in yyyy-MM-dd HH:mm:ss format
	Start string `json:"start,omitempty"`
}
