/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stcloud

type ChargesDetailsResponseDto struct {
	App              *App                 `json:"app,omitempty"`
	ChargeBase       string               `json:"chargeBase,omitempty"`
	DayUsageData     []DayUsageData       `json:"dayUsageData,omitempty"`
	MonthlyFeeAmount float64              `json:"monthlyFeeAmount,omitempty"`
	PeriodFeePeriods []MinPeriodFeePeriod `json:"periodFeePeriods,omitempty"`
	TotalAmount      float64              `json:"totalAmount,omitempty"`
	UsageAmount      float64              `json:"usageAmount,omitempty"`
}
