/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

// BasicOrganizationDto TODO godoc commenting
type BasicOrganizationDto struct {
	AuthMethods []BasicAuthMethodDto `json:"authMethods,omitempty"`
	Name        string               `json:"name,omitempty"`
	Status      string               `json:"status,omitempty"`
	UUID        string               `json:"uuid,omitempty"`
}
