/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stcloud

type FilterValue struct {
	AggType string `json:"aggType,omitempty"`
	FilterName string `json:"filterName,omitempty"`
	Key string `json:"key,omitempty"`
	Label string `json:"label,omitempty"`
	Name string `json:"name,omitempty"`
	Values []string `json:"values,omitempty"`
}
