/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stcloud

import (
	"time"
)

type TokenDto struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Enabled   bool      `json:"enabled,omitempty"`
	Id        int64     `json:"id,omitempty"`
	Name      string    `json:"name,omitempty"`
	Readable  bool      `json:"readable,omitempty"`
	Token     string    `json:"token,omitempty"`
	Writeable bool      `json:"writeable,omitempty"`
}
