/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

// AlertRule TODO godoc comment
type AlertRule struct {
	AccountEmail                          string                        `json:"accountEmail,omitempty"`
	AllowedAppTypes                       []int64                       `json:"allowedAppTypes,omitempty"`
	AnalyzingTime                         string                        `json:"analyzingTime,omitempty"`
	AppDisplayState                       string                        `json:"appDisplayState,omitempty"`
	AppID                                 int64                         `json:"appID,omitempty"`
	AppName                               string                        `json:"appName,omitempty"`
	AppState                              string                        `json:"appState,omitempty"`
	AppToken                              string                        `json:"appToken,omitempty"`
	AppType                               string                        `json:"appType,omitempty"`
	BackToNormalNeeded                    bool                          `json:"backToNormalNeeded,omitempty"`
	ChartKey                              string                        `json:"chartKey,omitempty"`
	Color                                 string                        `json:"color,omitempty"`
	CreatorEmail                          string                        `json:"creatorEmail,omitempty"`
	DefaultAggType                        string                        `json:"defaultAggType,omitempty"`
	Description                           string                        `json:"description,omitempty"`
	DisallowedAppTypes                    []int64                       `json:"disallowedAppTypes,omitempty"`
	Enabled                               bool                          `json:"enabled,omitempty"`
	EstimateOperation                     string                        `json:"estimateOperation,omitempty"`
	EstimateValue                         float64                       `json:"estimateValue,omitempty"`
	FilterValues                          string                        `json:"filterValues,omitempty"`
	FilterValuesObj                       []FilterValue                 `json:"filterValuesObj,omitempty"`
	IgnoreRegularEventsEnabled            bool                          `json:"ignoreRegularEventsEnabled,omitempty"`
	Integrations                          string                        `json:"integrations,omitempty"`
	LastDataReceivedDate                  int64                         `json:"lastDataReceivedDate,omitempty"`
	LastSent                              int64                         `json:"lastSent,omitempty"`
	LastTriggered                         int64                         `json:"lastTriggered,omitempty"`
	Metadata                              *interface{}                  `json:"metadata,omitempty"`
	MetricKey                             string                        `json:"metricKey,omitempty"`
	MetricLabel                           string                        `json:"metricLabel,omitempty"`
	MinDelayBetweenNotificationsInMinutes string                        `json:"minDelayBetweenNotificationsInMinutes,omitempty"`
	Name                                  string                        `json:"name,omitempty"`
	NotificationEmails                    []string                      `json:"notificationEmails,omitempty"`
	NotificationIntegrations              []NotificationIntegration     `json:"notificationIntegrations,omitempty"`
	NotificationsEnabled                  bool                          `json:"notificationsEnabled,omitempty"`
	Query                                 string                        `json:"query,omitempty"`
	ReportName                            string                        `json:"reportName,omitempty"`
	RuleKey                               int64                         `json:"ruleKey,omitempty"`
	RuleType                              string                        `json:"ruleType,omitempty"`
	Runbook                               string                        `json:"runbook,omitempty"`
	SavedQueryID                          int64                         `json:"savedQueryId,omitempty"`
	Schedule                              []AlertRuleScheduleWeekdayDto `json:"schedule,omitempty"`
	SematextService                       string                        `json:"sematextService,omitempty"`
	SendToEmail                           string                        `json:"sendToEmail,omitempty"`
	Timezone                              string                        `json:"timezone,omitempty"`
	UseOnlyAlertRuleIntegrations          bool                          `json:"useOnlyAlertRuleIntegrations,omitempty"`
	UserPermissions                       *UserPermissions              `json:"userPermissions,omitempty"`
	ValueColumnName                       string                        `json:"valueColumnName,omitempty"`
	ValueName                             string                        `json:"valueName,omitempty"`
}
