/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stcloud

// SavedQuery TODO godoc comment
type SavedQuery struct {
	AlertRule         *AlertRule       `json:"alertRule,omitempty"`
	AllowModification bool             `json:"allowModification,omitempty"`
	ApplicationID     string           `json:"applicationId,omitempty"`
	ApplicationName   string           `json:"applicationName,omitempty"`
	ApplicationToken  string           `json:"applicationToken,omitempty"`
	CreatorEmail      string           `json:"creatorEmail,omitempty"`
	ID                string           `json:"id,omitempty"`
	LabelColor        string           `json:"labelColor,omitempty"`
	LogseneAlertType  *interface{}     `json:"logseneAlertType,omitempty"`
	OwnerEmail        string           `json:"ownerEmail,omitempty"`
	QueryName         string           `json:"queryName,omitempty"`
	QueryString       string           `json:"queryString,omitempty"`
	UserPermissions   *UserPermissions `json:"userPermissions,omitempty"`
}
