/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stcloud

import (
	"time"
)

type MinPeriodFeePeriod struct {
	BrowserMonitors    int32     `json:"browserMonitors,omitempty"`
	Discount           float64   `json:"discount,omitempty"`
	FromDate           time.Time `json:"fromDate,omitempty"`
	HttpMonitors       int32     `json:"httpMonitors,omitempty"`
	ID                 int64     `json:"id,omitempty"`
	MinPeriodFeeAmount float64   `json:"minPeriodFeeAmount,omitempty"`
	OveragePercentage  float64   `json:"overagePercentage,omitempty"`
	PlanDataLimit      int64     `json:"planDataLimit,omitempty"`
	ToDate             time.Time `json:"toDate,omitempty"`
	UsedPlan           string    `json:"usedPlan,omitempty"`
	UsedPlanPeriodFee  float64   `json:"usedPlanPeriodFee,omitempty"`
}
