/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stcloud

type DailyDto struct {
	Day            int64 `json:"day,omitempty"`
	Failed         int64 `json:"failed,omitempty"`
	IngestedCount  int64 `json:"ingestedCount,omitempty"`
	IngestedVolume int64 `json:"ingestedVolume,omitempty"`
	StoredCount    int64 `json:"storedCount,omitempty"`
	StoredVolume   int64 `json:"storedVolume,omitempty"`
}
