/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stcloud

type AlertNotification struct {
	AppName      string `json:"appName,omitempty"`
	AppType      string `json:"appType,omitempty"`
	BackToNormal bool   `json:"backToNormal,omitempty"`
	CreateTime   string `json:"createTime,omitempty"`
	Sent         bool   `json:"sent,omitempty"`
	Text         string `json:"text,omitempty"`
	When         string `json:"when,omitempty"`
}
