/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stcloud

type UpdateAppInfo struct {
	Description        string  `json:"description,omitempty"`
	IgnorePercentage   float64 `json:"ignorePercentage,omitempty"`
	MaxEvents          int64   `json:"maxEvents,omitempty"`
	MaxLimitMB         int64   `json:"maxLimitMB,omitempty"`
	Name               string  `json:"name,omitempty"`
	Sampling           bool    `json:"sampling,omitempty"`
	SamplingPercentage int32   `json:"samplingPercentage,omitempty"`
	Staggering         bool    `json:"staggering,omitempty"`
	Status             string  `json:"status,omitempty"`
}
