/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stcloud
import (
	"time"
)

type NotificationIntegration struct {
	Applicability string `json:"applicability,omitempty"`
	CreateDate time.Time `json:"createDate,omitempty"`
	CreatedByOwner bool `json:"createdByOwner,omitempty"`
	CreatorId int64 `json:"creatorId,omitempty"`
	Id int64 `json:"id,omitempty"`
	IntegrationType string `json:"integrationType,omitempty"`
	Name string `json:"name,omitempty"`
	Params map[string]string `json:"params,omitempty"`
	State string `json:"state,omitempty"`
	UserId int64 `json:"userId,omitempty"`
}
